language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
script:
     - ./gradlew jatJar

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
